#include <iostream>
using namespace std;

int main()
{
   int n,a[99],sum=0;
   while(cin>>n&&n)
   {
       int i;
       for(i=0;i<n;i++)
       {
           cin>>a[i];
       }
       for(i=0;i<n;i++)
       {
           if(a[i]==100||a[i]==50||a[i]==5||a[i]==10||a[i]==2||a[i]==1)
           {
               sum++;
           }
           else
           {
               int t=a[i],sun=a[i]-100;
               while(sun>=0)
               {
                   sum++;
                   t=sun;
                   sun-=100;
               }
               if(sun==50)
               {
                   sum++;
                   break;
               }
               if(t==a[i])
               {
                   t=a[i];
                   sun=a[i]-50;
               }
               else
               {
                   t=sun+100;
                   sun+=100;
                   sun-=50;
               }
               while(sun>=0)
               {
                   sum++;
                   t=sun;
                   sun-=50;
               }
               if(sun==10)
               {
                   sum++;
                   break;
               }
               if(t==a[i])
               {
                   t=a[i];
                   sun=a[i]-10;
               }
               else
               {
                   t=sun+50;
                   sun+=50;
                   sun-=10;
               }
               while(sun>=0)
               {
                   sum++;
                   t=sun;
                   sun-=10;
               }
               if(sun==5)
               {
                   sum++;
                   break;
               }
               if(t==a[i])
               {
                   t=a[i];
                   sun=a[i]-5;
               }
               else
               {
                   t=sun+10;
                   sun+=10;
                   sun-=5;
               }
               while(sun>=0)
               {
                   sum++;
                   t=sun;
                   sun-=5;
               }
               if(sun==2)
               {
                   sum++;
                   break;
               }
               if(t==a[i])
               {
                   t=a[i];
                   sun=a[i]-2;
               }
               else
               {
                   t=sun+5;
                   sun+=5;
                   sun-=2;
               }
               while(sun>=0)
               {
                   sum++;
                   t=sun;
                   sun-=2;
               }
               if(sun==1)
               {
                   sum++;
                   break;
               }
               if(t==a[i])
               {
                   t=a[i];
                   sun=a[i]-1;
               }
               else
               {
                   t=sun+2;
                   sun+=2;
                   sun-=1;
               }
               while(sun>=0)
               {
                   sum++;
                   t=sun;
                   sun-=1;
               }
           }
   }
   cout<<sum<<endl;
   }
   return 0;
}
